using System;
using System.Collections.Generic;
using System.Text;
using VirtualGrid.Asus.Enums;

namespace VirtualGrid.Asus
{
    internal static class Maps
    {
        internal static readonly IReadOnlyDictionary<string, RogStrixKeyboardKey> RogStrix_G15_2021Map = new Dictionary<string, RogStrixKeyboardKey>() {
{ "Z", RogStrixKeyboardKey.Z },
{ "Y", RogStrixKeyboardKey.Y },
{ "X", RogStrixKeyboardKey.X },
{ "W", RogStrixKeyboardKey.W },
{ "V", RogStrixKeyboardKey.V },
{ "Up", RogStrixKeyboardKey.ArrowUp },
{ "U", RogStrixKeyboardKey.U },
{ "Tab", RogStrixKeyboardKey.Tab },
{ "T", RogStrixKeyboardKey.T },
{ "Space", RogStrixKeyboardKey.SpaceLed0 },
{ "Scroll", RogStrixKeyboardKey.GhostKey },
{ "S", RogStrixKeyboardKey.S },
{ "RightShift", RogStrixKeyboardKey.RightShiftLed0 },
{ "RightMenu", RogStrixKeyboardKey.GhostKey },
{ "RightControl", RogStrixKeyboardKey.RightCtrl },
{ "RightAlt", RogStrixKeyboardKey.RightAlt },
{ "Right", RogStrixKeyboardKey.ArrowRight },
{ "R", RogStrixKeyboardKey.R },
{ "Q", RogStrixKeyboardKey.Q },
{ "PrintScreen", RogStrixKeyboardKey.GhostKey },
{ "Pause", RogStrixKeyboardKey.GhostKey },
{ "PageUp", RogStrixKeyboardKey.GhostKey },
{ "PageDown", RogStrixKeyboardKey.GhostKey },
{ "P", RogStrixKeyboardKey.P },
{ "OemTilde", RogStrixKeyboardKey.TildeGraveAccent },
{ "OemSlash", RogStrixKeyboardKey.OemSlash },
{ "OemSemicolon", RogStrixKeyboardKey.OemSemicolon },
{ "OemRightBracket", RogStrixKeyboardKey.BracketRight },
{ "OemPeriod", RogStrixKeyboardKey.OemPeriod },
{ "OemMinus", RogStrixKeyboardKey.OemMinus },
{ "OemLeftBracket", RogStrixKeyboardKey.BracketLeft },
{ "OemEquals", RogStrixKeyboardKey.OemEquals },
{ "OemComma", RogStrixKeyboardKey.OemComma },
{ "OemBackslash", RogStrixKeyboardKey.OemBackslash },
{ "OemApostrophe", RogStrixKeyboardKey.OemApostrophe },
{ "O", RogStrixKeyboardKey.O },
{ "N", RogStrixKeyboardKey.N },
{ "M", RogStrixKeyboardKey.M },
{ "Logo", RogStrixKeyboardKey.GhostKey },
{ "LeftShift", RogStrixKeyboardKey.LeftShift },
{ "Left", RogStrixKeyboardKey.ArrowLeft },
{ "L", RogStrixKeyboardKey.L },
{ "K", RogStrixKeyboardKey.K },
{ "J", RogStrixKeyboardKey.J },
{ "Insert", RogStrixKeyboardKey.GhostKey },
{ "I", RogStrixKeyboardKey.I },
{ "Home", RogStrixKeyboardKey.GhostKey },
{ "H", RogStrixKeyboardKey.H },
{ "G", RogStrixKeyboardKey.G },
{ "Function", RogStrixKeyboardKey.GhostKey },
{ "Macro5", RogStrixKeyboardKey.LeftCtrl },
{ "LeftControl", RogStrixKeyboardKey.OemFunction },
{ "LeftWindows", RogStrixKeyboardKey.LeftWindows },
{ "LeftAlt", RogStrixKeyboardKey.LeftAlt },
{ "F9", RogStrixKeyboardKey.F9 },
{ "F8", RogStrixKeyboardKey.F8 },
{ "F7", RogStrixKeyboardKey.F7 },
{ "F6", RogStrixKeyboardKey.F6 },
{ "F5", RogStrixKeyboardKey.F5 },
{ "F4", RogStrixKeyboardKey.F4 },
{ "F3", RogStrixKeyboardKey.F3 },
{ "F2", RogStrixKeyboardKey.F2 },
{ "F12", RogStrixKeyboardKey.F12 },
{ "F11", RogStrixKeyboardKey.F11 },
{ "F10", RogStrixKeyboardKey.F10 },
{ "F1", RogStrixKeyboardKey.F1 },
{ "F", RogStrixKeyboardKey.F },
{ "Escape", RogStrixKeyboardKey.Escape },
{ "Enter", RogStrixKeyboardKey.OemEnterLed0 },
{ "End", RogStrixKeyboardKey.GhostKey },
{ "E", RogStrixKeyboardKey.E },
{ "Down", RogStrixKeyboardKey.ArrowDown },
{ "Delete", RogStrixKeyboardKey.GhostKey },
{ "D9", RogStrixKeyboardKey.D9 },
{ "D8", RogStrixKeyboardKey.D8 },
{ "D7", RogStrixKeyboardKey.D7 },
{ "D6", RogStrixKeyboardKey.D6 },
{ "D5", RogStrixKeyboardKey.D5 },
{ "D4", RogStrixKeyboardKey.D4 },
{ "D3", RogStrixKeyboardKey.D3 },
{ "D2", RogStrixKeyboardKey.D2 },
{ "D1", RogStrixKeyboardKey.D1 },
{ "D0", RogStrixKeyboardKey.D0 },
{ "D", RogStrixKeyboardKey.D },
{ "CapsLock", RogStrixKeyboardKey.CapsLock },
{ "C", RogStrixKeyboardKey.C },
{ "Backspace", RogStrixKeyboardKey.BackspaceLed0 },
{ "B", RogStrixKeyboardKey.B },
{ "A", RogStrixKeyboardKey.A },
{ "LinkLed4", RogStrixKeyboardKey.LedBar5 },
{ "LinkLed3", RogStrixKeyboardKey.LedBar4 },
{ "LinkLed2", RogStrixKeyboardKey.LedBar2 },
{ "LinkLed1", RogStrixKeyboardKey.LedBar1 },
{ "LinkLed0", RogStrixKeyboardKey.LedBar0 },
            { "LeftSide2", RogStrixKeyboardKey.DeleteInsert },
            { "LeftSide3", RogStrixKeyboardKey.MultimediaPlay },
            { "LeftSide4", RogStrixKeyboardKey.MultimediaPause },
            { "LeftSide5", RogStrixKeyboardKey.MultimediaPrevious },
            { "LeftSide6", RogStrixKeyboardKey.MultimediaNext },
            { "LeftSide7", RogStrixKeyboardKey.PrintScreen },
            { "Led3", RogStrixKeyboardKey.VolumeDown },
            { "Led4", RogStrixKeyboardKey.VolumeUp },
            { "Led5", RogStrixKeyboardKey.MicMute },
            { "Led6", RogStrixKeyboardKey.FanToggle },
            { "Led7", RogStrixKeyboardKey.RogKey }


        };

        internal static readonly IReadOnlyDictionary<string, AsusGenericKey> GenericKeyMap = new Dictionary<string, AsusGenericKey>();
    }
}
