name: Publish packages to nuget

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish VirtualGrid
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: VirtualGrid/VirtualGrid.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish VirtualGrid.Razer
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: VirtualGrid.Razer/VirtualGrid.Razer.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish VirtualGrid.Asus
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: VirtualGrid.Asus/VirtualGrid.Asus.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}